FROM eclipse-temurin:17
LABEL mentainer="bismoy.sanchi@gmail.com"

WORKDIR /app
COPY target/springBootDockerDemo-0.0.1-SNAPSHOT.jar /app/springBootDockerDemo.jar
ENTRYPOINT ["java", "-jar", "springBootDockerDemo.jar"]
