FROM eclipse-temurin:17

LABEL mentainer="newtest151285@gmail.com"

WORKDIR /app

COPY target/spring-boot-restfulwebservices-0.0.1-SNAPSHOT.jar /app/spring-boot-hello.jar

ENTRYPOINT ["java", "-jar", "spring-boot-hello.jar"]


